### PR TITLE
Modernize CMake

### PR DESCRIPTION
**Pull request by phprus**
1) The main goal is to simplify integration into other projects using add_subdirectory.
2) Using CMake 3.8+ features.
3) Fixed some configuration errors

Draft, as it pending PR #3, #4 and additional testing in my projects.

TODO: Remove "-w" and fix warnings in ``tests/btree/btree_test.cpp`` and ``tests/misc/bitvector_test.cpp``.

@greg7mdp Review my PR please.

### CODE REVIEW

**Comment by phprus** [comment]
@greg7mdp, what do you think about moving the ``gtl`` directory into the new ``include`` subdirectory?

This change isolates external projects from files, except the public ``gtl`` headers.

CMake changes, before:

https://github.com/greg7mdp/gtl/blob/b372a121e8872c82cc20decd44889cc4730d32a5/CMakeLists.txt#L31-L34

after:

```cmake
 target_include_directories( 
      ${PROJECT_NAME} INTERFACE 
      $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include> 
      $<INSTALL_INTERFACE:include>) 
```

**Comment by greg7mdp** [comment]
> about moving the `gtl` directory into the new `include` subdirectory?

Not sure what you are asking? Do you want to rename `gtl` to `include`?

**Comment by phprus** [comment]
Before: ``${PROJECT_SOURCE_DIR}/gtl/phmap.hpp``
  After: ``${PROJECT_SOURCE_DIR}/include/gtl/phmap.hpp``

  ``include_directories`` for target ``gtl``: ``${PROJECT_SOURCE_DIR}/include`` (now: ``${PROJECT_SOURCE_DIR}``)

There will be no visible changes for gtl users.

**Comment by greg7mdp** [comment]
Sounds OK with me. I'm still not clear what the benefit is? Sorry I'm not very good with cmake.

**Comment by phprus** [comment]
``CMakeLists.txt``:

```cmake
add_subdirectory(greg7mdp/gtl)

add_executable(my_exe main.cpp)
target_link_libraries(my_exe PRIVATE gtl)
```

``main.cpp``:
```c++
#include <gtl/phmap.hpp>

// Before - OK
// After - file not found error
#include <tests/btree/btree_test.hpp>

int main()
{
  return 0;
}
```

**Comment by greg7mdp** [comment]
Thanks for the explanation. Changes look good! Really appreciate it!

**Comment by phprus** [comment]
``bit_vector`` has error on 32-bit platform. But the error is not related to this PR.

All my integration tests passed:
macOS - Xcode 13
Linux - gcc-8,9,10; clang-11,12(libstdc++)
Windows - MSVC 2019

**Comment by phprus** [comment]
After this PR, I will prepare a CI improvement and a fix of some compiler warnings.

Updated CI will show an error when ``bitvector`` testing on 32-bit Windows. I don't know how to fix it yet.

**Review by greg7mdp — APPROVED** [review]
Thanks a lot @phprus , amazing work!

**Comment by greg7mdp** [comment]
> bit_vector has error on 32-bit platform. But the error is not related to this PR.

@phprus I'm looking at this

**Comment by greg7mdp** [comment]
@phprus actually I just fixed the 32bit CI issuie a couple minutes ago.

**Comment by phprus** [comment]
@greg7mdp
Please see PR #6
The updated CI supports 32-bit windows.

**Comment by greg7mdp** [comment]
@phprus wow, thanks.! I need to go outside to shovel snow, but I'll have a look soon after. Really appreciate all the great work you are doing.

**Comment by phprus** [comment]
PR #6 rebased and ready for review.

**Pull request merged**
