### PR TITLE
Fix incorrect SFINAE

### PR DESCRIPTION
**Pull request by phprus**
and format specifies warnings.

### CODE REVIEW

**Comment by greg7mdp** [comment]
Thanks for the fix. However I wonder if the `enable_if` are correct, they look like the `WRONG` example in https://en.cppreference.com/w/cpp/types/enable_if.

**Comment by phprus** [comment]
Function templates vs class templates.

Function templates - wrong (and ``WRONG`` example on cppreference).

Class template: https://cpppatterns.com/patterns/class-template-sfinae.html

**Comment by greg7mdp** [comment]
Thanks @phprus

**Comment by greg7mdp** [comment]
After your merge I have these warnings with gcc:

```
[ 38%] Built target test_bit_vector
/c/greg/github/gtl/examples/misc/memoize2.cpp:116:69: warning: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
    printf("cached_nth_prime(%llu):   => %llu in %10.3f seconds\n", idx,  x, sw.since_start() / 1000);
                             ~~~~                                   ^~~
                             %lu
/c/greg/github/gtl/examples/misc/memoize2.cpp:116:75: warning: format specifies type 'unsigned long long' but the argument has type 'unsigned long' [-Wformat]
    printf("cached_nth_prime(%llu):   => %llu in %10.3f seconds\n", idx,  x, sw.since_start() / 1000);
                                         ~~~~                             ^
                                         %lu
```

**Comment by phprus** [comment]
@greg7mdp 
Fixed in #10
I am sorry.

**Pull request merged**
